### ISSUE TITLE
`sonar help` should print version and build date

### ISSUE THREAD

**Issue by lars-t-hansen** [NordicHPC/sonar#101]
I think it will be helpful for sonar to be able to self-identify.

**Comment by bast** [comment]
Yes absolutely. This looks like something I should be able to solve. Taking it.

**Comment by bast** [comment]
And we are few months later ... reminding myself of this issue.

**Comment by lars-t-hansen** [comment]
Poaching since we want this for the new "release procedures".

Version is trivially gotten from Cargo.  The build time we can get with https://github.com/AlephAlpha/build-time which is MIT license and we can crib the code we need to avoid taking a dependency.
