### ISSUE TITLE
Bump the version number for other things than file format changes

### ISSUE THREAD

**Issue by lars-t-hansen** [NordicHPC/sonar#102]
As we're getting closer to deploying sonar in earnest - testing so far proves that it has real utility - it will be helpful for us to update the version number more frequently, so that we can more easily track the version that's being used.  For example, the recent upgrade to reading data from /proc warranted such a change (though we did not make it).  I guess we'll have to figure out some sensible policies for when to bump the version.

**Comment by bast** [comment]
I think we should bump on any PR that we intend to use on production server so that we can trace back format changes.

**Comment by lars-t-hansen** [comment]
I will formalize that rule and add it to the README.
