### ISSUE TITLE
System configuration data

### ISSUE THREAD

**Issue by lars-t-hansen** [NordicHPC/sonar#105]
At the moment, the sonar report contains a single datum on the system we're looking at, `cores`.  My sonar consumer, sonalyze, ignores this datum - it needs to know that value for some things, but it needs to know so much more (memory installed, number of accellerator cards, and the features of those cards; eventually, network interconnects and topology, probably).  So sonalyze instead reads a user-provided config file that has system configuration data.  (Just a json thing.)

It would probably be in our best interest to figure out how to do this best.  Clearly sonar can provide up-to-date data but they hardly ever change, so why should those data be in every record?  And can it provide all the necessary data?  And at what cost?  On the other hand, manually maintaining these configuration data separately is a chore and error prone.  On the third hand, not having the configuration data baked into the measurement data allows the configuration data to be updated, augmented, and in other ways improved over time without having to worry about the measurement data, which are static.

It may be that some consumers, eg jobgraph, have simple needs, and that baking cpus and memory into the sonar data is the right thing for it.  But even then the question is whether those data might not better be obtained, say, every 24h by a separate script and logged into a separate file.

This is also not completely unrelated to #44, since having a precise machine config available to sonar when sonar runs would allow a system configuration check of the type mentioned in that bug to be targeted, effective, or unnecessary.

- [x] #142
- [x] #148
- [x] #149

**Comment by bast** [comment]
It's a great point. Thinking ...

**Comment by lars-t-hansen** [comment]
Related: https://github.com/NAICNO/Jobanalyzer/issues/97

**Comment by lars-t-hansen** [comment]
Related: #72, because the "GPU status", like the number of cores or the amount of memory, is a feature of the machine, not the individual job, but unlike those it is a temporal feature of the machine.  (GPUs can enter failure states, and are like peripherals in that regard, and unlike typical CPUs.)  In the patch on that ticket I have opted to include gpu status the job record, mostly because I need these data soonish, but we should discuss whether there are better places.

**Comment by bast** [comment]
I am also tending towards recording hardware data and process data into two separate files on separate time scales.

**Comment by bast** [comment]
What I liked about writing everything to one place is that we can output to stdout and the user can decide where that goes. So maybe it could still go to the same file/output? But on different time scales? It could be controlled by flags and the cron job could decide which one it wants to query.

**Comment by lars-t-hansen** [comment]
That reminds me, cron may not be the best way to run sonar.  We had a situation here where a node was in nologin state for a day in order to be reserved for some work; nologin also disabled the cron job, so we got no data while the special job was running, even though that would have been useful.  It's possible that we should discuss how to daemonize sonar more properly.

**Comment by lars-t-hansen** [comment]
After pondering this a bit (and running into the need for writing an accurate configuration file for Fox, which is a chore, and it has less than 40 nodes):

- sonar should probably have a command, "config", that extracts the system configuration from /proc/cpuinfo, /proc/meminfo, and nvidia-smi / rocm-smi when available (and detecting whether they are available is a thing)
- this should be run "now and then", maybe once per 24h, by cron
- the data should be printed on stdout as for "ps"
- the data format should be such that the data can be printed into the same stream as that used by ps, this is most convenient
- we need to have some safeguard against ps and config trying to write at the same time
- on the ingest side, sonarlog will extract config data from the stream if asked to, and will discard it otherwise

For the format, most obviously, we introduce a v0.8.0 record format and add a "type" field, which, if present, can state the type of record and if not present, defaults to "ps".  The mutex on the output probably favors having config not as a stand-alone command but as a combined "ps+config" command or as having --config as a flag to ps.

**Comment by lars-t-hansen** [comment]
I've hacked up a prototype of the config command (in Go) for Jobanalyzer: https://github.com/NAICNO/Jobanalyzer/tree/main/sysinfo

**Comment by lars-t-hansen** [comment]
See #142, which implements `sonar config` (see above) as `sonar sysinfo`.  The data format is JSON, and I think this is OK - in practice, `sonar ps` and `sonar sysinfo` will be run by separate scripts at separate times in separate cron control lines, and the formats need not be compatible.  JSON was chosen because the existing format (for the prototype) is JSON; let's discuss in #142, if necessary.

**Comment by lars-t-hansen** [comment]
This has been fixed.  `sonar sysinfo` reports the system configuration and the then-redundant fields have been removed from the sonar output.
