### ISSUE TITLE
Data volume, disk and network contention

### ISSUE THREAD

**Issue by lars-t-hansen** [NordicHPC/sonar#106]
I was reading the RRD documentation and started thinking about scale; "what does success look like?"

[Betzy has 1344 nodes](https://documentation.sigma2.no/hpc_machines/betzy.html).  If we run sonar on each node every 5 minutes, that's 12 runs per node per hour, giving an aggregate number of 16128 runs per hour and 387072 per day -- and almost 5 per second of they are evenly distributed by time.  Each run produces some KB of data, CSV is not compact.  (I had some measurements from Fox but I can't remember them; Fox data were quite a bit larger than data from our ML nodes, and Fox nodes are the same size as Betzy nodes, 128 cores.)  But say 4KB of data per run just to have a number, this is 1.5GB per day and I believe conservative.  As it is, the runs are however all synchronized by cron and by the architecture of sonar they all hit the same centralized disk.  Disk / network traffic will be highly correlated.  And even if it were spread out there would be significant traffic to and from the shared disk.

Obviously this is a very powerful system and I don't know how much of a problem the network traffic would be.  I don't know if we could mitigate problems by using, say, multiple directory trees the way we are using multiple files, one per node.  (As it is, each directory will have > 1344 files, one per node.)

Any query on that type of data volume with that type of representation that is for more than a few days is likely to be very slow, too.

An alternative architecture to append-csv-to-file might look a bit more like what I understand RRD to be like:

- acquired data are sent by network to centralized daemon which can handle large data volume
- data are compact
- daemon handles an actual database with efficient data representation in the background
- queries against the database provide an efficient and pre-filtered data stream

Fox will help us understand what multi-node systems and jobs look like, but unfortunately Fox will not give us enough data to contend with scale issues, as it has only 24 nodes.

**Comment by lars-t-hansen** [comment]
I found some Fox data.  One time step on one node generated 61 lines of output for a total of 11001 bytes.  (This happened to be the busiest node, the average could look like about 9KB per time step per node.)

Considering a still-flexible but more compact format, each field name would be a single byte and have a defined data type; time stamps would be 40 bits of seconds-since-epoch + 8 bits of tz; most integer data (job numbers etc) would be two-byte or four-byte integers; zero fields would be absent (esp important for gpu data, most nodes have no gpus).  This would yield records of approximately (some fields are variable length but a NUL or other non-printable terminator will work, as will a one-byte length field) 64 bytes on average, depending on host name and user name lengths; compared to an average of 180 bytes now, for an almost 3-fold savings.  That might matter at these volumes - we get back to 4KB per node time step.

Anyway, that's just a for-instance; the field is wide open.

**Comment by lars-t-hansen** [comment]
And it'll possibly be helpful to stagger runs on different nodes somehow (random delay within sonar?) to avoid correlated disk/network traffic.

**Comment by lars-t-hansen** [comment]
Default values is #74.

**Comment by bast** [comment]
The data volume generated on Saga is currently around 25 MB/day but that is still using the old format.

**Comment by lars-t-hansen** [comment]
> The data volume generated on Saga is currently around 25 MB/day but that is still using the old format.

And with a 30-minute sample interval?

**Comment by bast** [comment]
5 minute interval

**Comment by lars-t-hansen** [comment]
FWIW, in my meeting with the Fox admins they brought up the issue of storing data on a shared disk and expressed a general dislike for the architecture, preferring some sort of network transport of the data to a daemon running elsewhere.  This is not on my list of urgent concerns, but I'll likely sketch out an experimental architecture for this over the winter, once we have some experience with behavior and data volumes from Fox (in addition to Saga, of course).

**Comment by bast** [comment]
I understand their concern. We had to start simple otherwise this would have never started.

**Comment by lars-t-hansen** [comment]
> I understand their concern. We had to start simple otherwise this would have never started.

Quite so, and I believe simplicity should still guide us.  I think their concern is in part that the shared / cluster file system is getting hammered pretty hard already and is not very stable ("prone to hanging" came up).  Introducing a network transport and a daemon on the other end adds several sources of unfortunate complexity - the daemon and its disk have to be up, and there must be mechanisms for keeping them up; the transport has to be reliable (slower, more prone to hanging) or we have to have some kind of integrity check on the data and some way of assessing how much data we lose (complex, brittle).

**Comment by lars-t-hansen** [comment]
My old job was in IoT and over the weekend I realized that a supercomputer is just a small IoT system, from a point of view that is much like the Sonar/Jobanalyzer point of view.  (1344 deployed units? It's nothing.)  The most reasonable technology for transport of sonar data over the network may well be an established messaging protocol such as MQTT.  MQTT strikes a balance between confidentiality, authorization needs, performance, and quality of implementations.  But there are others, such as CoAP, and probably nothing should be picked until the parameters of the implementation and architecture are well understood and agreed upon.

**Comment by lars-t-hansen** [comment]
For the time being, I'll be implementing network-based transport external to sonar - sonar will continue to write to stdout as it currently does, but (experimentally) I'll be piping the output into a transporter that communicates with a remote agent that will store the dta.
