### ISSUE TITLE
Always write something

### ISSUE THREAD

**Issue by lars-t-hansen** [NordicHPC/sonar#107]
At the moment, `sonar ps` will not write anything if there are no jobs running worth reporting about.  However, for https://github.com/NAICNO/Jobanalyzer/issues/104 I need `sonar ps` to reliably write a record every time it is invoked, because the presence of data with the timestamp in the timeline is used as a signal that the system was up at that time.

Two obvious ways to fix this:
- A: `sonar ps` always writes at least something, even if only a synthetic record
- B: `sonar ps` invoked with a flag (say, --always-write) always writes at least something, ditto

Then, the secondary question:
- X: write a synthetic record always
- Y: write a synthetic record only if there is nothing else to write

Possibly there are natural affinities here (Y with A, X with B) but I'm uncommitted about that.  I'm most happy with Y.

Clearly there are some other options:
- Don't place this burden on sonar but use some other mechanism for uptime monitoring
- Make sonar do this, but log the data some other place than in the normal job data stream

Frankly though I think it fits in pretty well with whatever else sonar is doing, and since the sonar data require more or less sophisticated disentangling already anyway, and in the common case already contain the data we want for uptime monitoring, there doesn't seem to be any need to add more output files.
 
@bast, any opinions about this?

**Comment by bast** [comment]
Many UNIX tools produce no output but when teaching those tools to people new to UNIX/Linux, they are often surprised by that. Which over the years showed me that it is not good UI to not return anything. But I know that was not the point here.

Good point of being able to use sonar as a "heartbeat".

Some ideas as alternative to purely synthetic record:
- if no process makes it above threshold, we show the one that used most of resources, even if they were tiny?
- if no process makes it above threshold, we list the sonar process? because it is always there? or isn't it?

**Comment by lars-t-hansen** [comment]
I like the option of listing the sonar process, among your two suggestions.  That said:

The thing about a truly synthetic record that is good is that it will stand out on the client side - it is easy to filter it when it's not needed (fields have completely predictable names, and probably single field values but certainly combinations of field values can be guaranteed never to clash with user data), and easy to look for it when it is needed (for the same reason).  Using a real process means that the conditions for removing or using are slightly more complicated.

Worse than that, I worry about tools becoming confused.  Last week I was trying to set up a user to run sonar here, and it turned out that the user name `sonar` was already taken by a real user.  Possibly somebody else will have a program called sonar, too.  There are 25,000 github repos with "sonar" in the name, and "sonar" is a popular (apparently) source code analysis tool.

**Comment by bast** [comment]
Avoiding confusion is really important. Maybe the most intuitive thing would be a record that prints that nothing was detected above threshold. This would also motivate us to define what the null value is. It would be the "None" of well defined types and we could then search for that and also filter that out.

**Comment by lars-t-hansen** [comment]
OK, I think we're mostly aligned here.  (I don't know where you're going with the idea of a null/None value, but I don't see any conflicts with the needs I have per se.)  My current draft, which is complete apart from any syntactic changes we make, is in #112.  A synthetic record with a combination of recognizable field values (pid=job=0, user="_sonar_", command="_heartbeat_", etc) is printed in the case when nothing else is printed for an invocation of `sonar ps`.  Fields that have default values would be omitted on output as for other records, once we fix that bug.  I think this solution is close to what you're suggesting.

**Comment by bast** [comment]
This sounds like a good solution to me. My null/none comments indeed are not so relevant since the default values are not printed.

**Comment by lars-t-hansen** [comment]
I'll run some more experiments tomorrow with that draft and a complementary patch on the ingest side, and offer up the sonar fix when I feel it's solid.
