### ISSUE TITLE
procfs must be more clever about jobs in the X and Z states

### ISSUE THREAD

**Issue by lars-t-hansen** [NordicHPC/sonar#111]
Fun error message:
```
INFO: procfs failed: Could not parse sess from /proc/2839925/stat: 2839925 (python3) X 0 -1 -1 0 -1 4243524 0 0 0 0 0 0 0 0 20 0 0 0 10643829 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 17 3 0 0 0 0 0 0 0 0 0 0 0 0 0
```
sess is the sixth field, here -1.  In the manpage the format is %d, but the procfs code uses a usize parser.  The reason it's -1 is the X in the third field: the process is dead, we just caught it at the wrong time.

This particular problem is benign and we'd probably reject the record anyway, it has no useful information.

It's possible that the right thing here is:

- be more careful about using parsers that correspond with what the manpage requires
- handle out-of-range values in some sensible way
- maybe look to the state field to make sure the job is in a sensible state before deciding what to do next

**Comment by bast** [comment]
For the moment I like the "maybe look to the state field to make sure the job is in a sensible state before deciding what to do next" the most.

**Comment by lars-t-hansen** [comment]
This is a regression, see the linked Jobanalyzer bug above.  We're going to need a sensible strategy to handle job states.  Taking this.

**Comment by lars-t-hansen** [comment]
There's another problem having to do with jobs that have been running for a very short time:
```
$ target/debug/sonar ps | grep NaN
v=0.7.0,time=2023-10-25T17:03:06+02:00,host=bling,cores=8,user=larstha,job=0,pid=1443389,cmd=grep,cpu%=NaN,cpukib=424,gpus=none,gpu%=0,gpumem%=0,gpukib=0,cputime_sec=0
v=0.7.0,time=2023-10-25T17:03:06+02:00,host=bling,cores=8,user=larstha,job=0,pid=1443388,cmd=sonar,cpu%=NaN,cpukib=520,gpus=none,gpu%=0,gpumem%=0,gpukib=0,cputime_sec=0
```
This is a simple calculation error though, but it needs to be dealt with.

**Comment by lars-t-hansen** [comment]
(Duh, that's #113.)

**Comment by lars-t-hansen** [comment]
Test case coming with patch on #94.
