### ISSUE TITLE
Guard against multiple concurrent invocations

### ISSUE THREAD

**Issue by lars-t-hansen** [NordicHPC/sonar#123]
As a prerequisite for deploying Sonar on Fox, the admins are requesting that there be a guard against sonar processes hanging and using up system resources, and are suggesting we use a lockfile for that.  As this is a feature for a subset of installations and not all installations, I imagine a command line option to `sonar ps` along the lines of `--lockfile /path/to/lockfile/dir`.  It would be ideal for the lockfile dir to be on a local file system but it would be best for us not to require that, so the actual lockfile name would probably be something like `/path/to/lockfile/dir/sonar-lock.<hostname>` where the hostname would be the host's detected host name.  The semantics would roughly be that sonar exits immediately if that file exists when sonar starts up (I need to read up on best practices).  Open question: What to do if the directory does not exist.

On the one hand, sonar already has some guards against hanging - we time out on subprocesses and so on.  On the other hand, we have already experienced hanging and some unfortunate fallout from that, see bug #100.

To test that this works it'll be useful to have some sort of testing mode that makes sonar sleep for a bit, and maybe an exit code from sonar that exposes the early exit.

**Comment by bast** [comment]
That's a good idea I never thought about. Also the testing mode (last time I tested this I had to edit the code so it would be nice to not have to do that).

**Comment by bast** [comment]
Now that I read again, is the goal that sonar writes a lock file, writes the file, then releases the lock? For every hostname?

**Comment by lars-t-hansen** [comment]
Well, the goal as such is that there is never more than one sonar process running at a time on any one node, and if a second process attempts to start while one is running then it needs to detect this and quit early.  The lockfile solution would be that on a given node called N, sonar, when it starts, would attempt to create the file /path/to/lockdir/sonar-lock.N.  If that fails it would exit.  Otherwise it would probably write its pid into that file, and close it.  Then it would do what it normally does and write output to stdout.  Then it would delete the lockfile and exit.  This is really only sensible if the lockfile is on disk that's local to the node (otherwise we're back to hammering on a shared filesystem again) but the general assumption seems to be that there are such file systems everywhere.

**Comment by bast** [comment]
Good. Then I get it. Seems a bit "paranoid" but is probably reasonable.
