### ISSUE TITLE
Simplify interface?

### ISSUE THREAD

**Issue by lars-t-hansen** [NordicHPC/sonar#129]
Sonar currently has only one command, `ps`.  The other command, `analyze`, is a stub and is anyway subsumed by [sonalyze](https://github.com/NAICNO/Jobanalyzer).  We could remove the command layer from sonar.  It's not urgent to do so, but I believe that other monitoring we might do will work just as well as standalone programs, eg the sysinfo utility that is part of [JobAnalyzer](https://github.com/NAICNO/Jobanalyzer), and so simplifying sonar could be sensible.

**Comment by bast** [comment]
I agree with simplifying the interface and dropping `analyze` in favor of sonalyze. Good idea. I will take this one.

**Comment by bast** [comment]
Good that I was slow :-) Let's say that we have verbs, and then we would need only two, which ones would be intuitive?
- `sonar sysinfo`
- `sonar snapshot` ?

**Comment by bast** [comment]
... and  `sonar help` from #101

**Comment by lars-t-hansen** [comment]
I think we close this as completed-by-side-effect-of-other-work.  At the moment we have `sonar ps`, `sonar sysinfo`, and `sonar help`; `sonar analyze` was removed as part of removing the dependency on clap.   In #101 we improve the `help` verb.  It's possible that `ps` should be renamed as `snapshot` or `sample` but then this is not urgent and should be filed as a separate bug if desired.
