### ISSUE TITLE
Add `sysinfo` verb

### ISSUE THREAD

**Issue by lars-t-hansen** [NordicHPC/sonar#142]
Right now I have a standalone `sysinfo` program (https://github.com/NAICNO/Jobanalyzer/blob/main/code/sysinfo/sysinfo.go) that queries the configuration of the node and prints the data on stdout (as json), from where it is forwarded to the analysis machine.  On the ML nodes it is now run on boot + once a day.  I would like to have fewer programs to upgrade on all the nodes (currently there are three + a script and I'd like to reduce that to one + a script) and I think folding `sysinfo` as a verb into sonar makes a lot of sense.  It would not be much code (source or binary), we have most of the bits already.

**Comment by bast** [comment]
Sounds good.
