### ISSUE TITLE
Add a random-delay switch

### ISSUE THREAD

**Issue by lars-t-hansen** [NordicHPC/sonar#143]
Currently there are two programs in the sonar pipeline on most nodes: sonar collects data and prints it on stdout, and another program `exfiltrate` (https://github.com/NAICNO/Jobanalyzer/blob/main/code/exfiltrate/exfiltrate.go) takes the output and forwards it to the analysis machine in a sane way, so that we don't have to store anything on shared disk - a no-no from the Fox admins (and I agree with them).  Exfiltrate used to be more complicated but now it is two things: a random delay before sending, and then retry logic to try resending if the first attempt failed.  The retry logic has two parameters, the number of times to try and the number of seconds to wait between each attempt.  The random wait before sending is to avoid overloading infrastructure along the way and at the endpoint and I think it's desirable.

It turns out that curl can do all the retry logic for us, and it can read data from stdin too.  So the pipeline could really just be `sonar|curl` if we can incorporate the random wait before the first send.  We could do this in the shell script with something like `sleep ((RANDOM % wait-time))` but it might be cleaner to just build this into sonar to keep the number of moving parts small.  I envision a switch `--random-wait <seconds>`.  It'll be important to make sure the lock file is relinquished before waiting (if applicable).

Also see #142, which is the sibling problem of getting rid of another component by folding it into sonar.

**Comment by bast** [comment]
That sound very reasonable.

**Comment by lars-t-hansen** [comment]
I think that we should only do the `--random-wait` if we fold the https exfiltration into sonar, otherwise we are already running a shell pipeline and can do this (where "240" is the sleep window, 4 minutes is probably OK if we run sonar every 5, and "11" retries with exponential backoff starting at 1s brings us up to about 30 minutes):

```
$ sonar ps --exclude-system-jobs --min-cpu-time=60 --rollup | \
(sleep $((RANDOM % 240)) ; curl \
--data-binary @- \
-H 'Content-Type: text/csv' \
--netrc-file secrets/exfiltrate-auth.netrc \
--retry 11 --retry-connrefused \
naic-monitor.uio.no/sonar-freecsv?cluster=saga.sigma2.no)
```

**Comment by lars-t-hansen** [comment]
Using the above structure - with some tweaks to handle edge cases when there is no output b/c error or the lock file cannot be acquired - works really well, so there's no reason for this.
