### ISSUE TITLE
Process names containing spaces are truncated

### ISSUE THREAD

**Issue by lars-t-hansen** [NordicHPC/sonar#36]
Firefox creates a bunch of processes called "Isolated Web Process".  sonar shows these as just "Isolated", which is unfortunate information loss.  Would probably be good to fix this, the space could be shown literally (process names could be quoted) or as _ or with some sort of escape.  It could look like the underlying problem is the split_whitespace() call in ps.rs.

**Comment by bast** [comment]
Thanks for catching this! This should indeed be easy to fix.
