### ISSUE TITLE
Large output is a reality, and killing the subprocess is not a workaround

### ISSUE THREAD

**Issue by lars-t-hansen** [NordicHPC/sonar#51]
Basically, running ps on "big enough" systems or asking for the unfiltered ps output will create enough output to make the pipe fill up and the process hang, in turn causing the subprocess to be killed by the timeout in command.rs: https://github.com/NordicHPC/sonar/pull/50#issuecomment-1600497721.

There are really two bugs here.  One is that if the subprocess is killed there should be some report up the call chain so that whoever started the process can take evasive action, log an error, etc.  (In general there are probably good reasons why we should try to catch errors high up and log them.)  The other is that we need to fix the hangs caused by too-large output.

**Comment by lars-t-hansen** [comment]
Propagating errors from command.rs moved to #53, proper logging moved to #52, the present bug is about handling large output from the subcommand.

**Comment by bast** [comment]
Thanks! I am sorry because I knew about this problem but did not document it properly. Reviewing this and other PRs ...
