### ISSUE TITLE
Job filtering should be post-accumulation, and must be more subtle

### ISSUE THREAD

**Issue by lars-t-hansen** [NordicHPC/sonar#73]
At the moment, sonar filters processes and jobs early based on the raw ps output: if the cpu percentage of the process itself is below a threshold or its current memory usage is below a threshold, then the record is discarded.  This is iffy for several reasons:

* multiple processes can be accumulated into a job and in total they may create a load that is above the cutoffs, yet none of those processes will be considered
* for `--batchless` in particular, but I suspect even in general, the root process of a job may not be doing much but it may well be that it should be present to represent the job as a whole
* the cpu percentage is, as we've seen in #68, not a high-quality number (and in particular it is not a sample)
* filtering, even when based on good samples such as for mem_percentage, creates a log that has holes, which can be surprising to log consumers, jobs will appear to have stopped and then restarted, and there can be confusion about whether a job ID seen after such a hole is the "same" job or a "new" job

I suspect that we should do multiple things here:

* filtering should be applied to the accumulated job records, if at all
* filtering might be disabled altogether for `--batchless`
* filtering by cpu% probably needs to be removed, but cputime is not much of a substitute since that is a cumulative value and only the consumer of the log can reconstruct a sample-ish value for it

It's possible this is a good time to discuss why we're doing filtering and what we're really interested in getting rid of.  Looking at my own logs, I'd be more interested in getting rid of jobs by root and zabbix than user processes, for example.

**Comment by bast** [comment]
Thanks for good points!

My motivation for filtering was:
- smaller log files to not fill the disk (maybe I was too careful)
- smaller log files to have faster analysis later to not read through many zeros (also this is perhaps premature optimization)

**Comment by lars-t-hansen** [comment]
Oh, and we filter twice and I forgot the other one: for non-`--batchless` operation we filter when we run ps.  This filtering is coarse and probably error prone, it's meant to match pcpu and pmem, and that again gets us into trouble with the meaning of the pcpu value, and it embeds an "expected" number of spaces, which is probably asking for trouble too.  Again I think it would probably be best to apply this filtering later.

**Comment by lars-t-hansen** [comment]
Establishing an evolving task list:

- [ ] remove two instances of ad-hoc filtering from ps.rs, see above
- [ ] implement the option of filtering during or immediately before we write
- [ ] establish appropriate filters, eg, it may be useful to cutoff for little cpu or memory use, and it may be useful to filter by user name
- [ ] establish the appropriate filtering defaults for different operation modes (`--batchless` vs not)
- [ ] maybe add command line options to control this

**Comment by lars-t-hansen** [comment]
Some sensible filtering options, these could all in principle be exclude/include:

- average cpu time over the lifetime of the process below threshold (what we currently do)
- memory occupancy at present below threshold (what we currently do)
- user id below 1000 (ie, system process)
- user id matches in set of ids
- user name matches string or matches in set of strings

We don't want to make it too complicated, because the front ends will have their own filtering; the filtering here is just to reduce data volume.
