### ISSUE TITLE
pid is a unique key for results from the subprocesses

### ISSUE THREAD

**Issue by lars-t-hansen** [NordicHPC/sonar#76]
For ps, nvidia-smi, and rocm-smi (and in general for all future uses like these) the pid will be a unique key (for a given pid there is only ever a single user and a single command, at least per invocation of ps etc).  In ps.rs we still use the tuple (user, pid, command) as the key for various processing steps.  This is not necessary and obscures what happens.  It's probably just an effect of an older design that has yet to be cleaned up completely.

**Comment by bast** [comment]
Yes you are right. Historically it started with (user, command) as key. The pid was added later.
