### ISSUE TITLE
job_id is possibly a unique key for job information, but "it's complicated"

### ISSUE THREAD

**Issue by lars-t-hansen** [NordicHPC/sonar#78]
Follow-on from #76.

Currently the key for the "job" table in ps.rs is (user, job_id, command).  It's not completely clear why the user name or command are desirable here.

On the one hand, the job id should be a unique key for the job.

On the other hand: for a given job there could be many processes each with their own command, and with the command being part of the key each will have its own line in the sonar log.  This may be what we want (discuss), since it gives postprocessing a chance to see this.  (The alternative would be for the sonar log to be more complex and contain multiple commands.)  More far-fetched, each of those processes could have its own effective UID, so there could be multiple users, too.

On the third hand: it's a little strange that sonar would roll up multiple `python` processes into one record but distinguish this from, say, a `python3.9` process belonging to the same job.  In this case, it would be more natural for sonar to produce a record for each process, all of them tagged with the same job number.

This may become a discussion about what sonar should do, and what the postprocessor should do.

**Comment by bast** [comment]
Another historical note: (user, command) was there before we figured out how to get the Job ID easily.

**Comment by lars-t-hansen** [comment]
Although it may be that in cleaning this up, we have to be extra careful when we use job_id==0 as "unique job without job id", which is its current meaning.  Not too hard internally in sonar, but requires care in the external representation and in the frontend.

**Comment by bast** [comment]
> Excellent. So that probably means that the "rollup" code that is in extract_ps_info and extract_gpu_info (where there's a chance that a pid mapping is in the hashtable already) is also redundant. This code has been puzzling me for a while. I know for a fact that ps will not produce output with a duplicate pid, and I didn't think the GPU code would either, but when I last touched this code I just kept what was there from before. But that can probably be rewritten, then.

That code grew out of summing pid with same process name and user name into one entry. But over time I added more things to it and now it probably does things too much in a too byzantine way.

**Comment by lars-t-hansen** [comment]
I've rewritten this code to reduce the confusion.  In the rewrite, the pid is the unique key for a process; processes are not merged but tagged with their job ID, and a record is written for each process.  The post-processor must merge processes belonging to the same job if it wants to.  The output volume does not seem to change as a result of this, nor was it really expected to.  Patch coming.

**Comment by bast** [comment]
That's awesome. Thanks!
