### ISSUE TITLE
Read data directly from /proc

### ISSUE THREAD

**Issue by lars-t-hansen** [NordicHPC/sonar#86]
Right now we're running `ps` but there are good reasons not to do so:

- needs to run a subprocess which needs to parse its command line, figure out what to do, obtain data, and generate textual data, which we then have to read and re-parse
- we need a lot of data from the subprocess to generate a process tree, which makes the previous problem quite a lot worse

By reading data from /proc/PID/status (mostly) we would streamline this process and avoid unnecessary work.

**Comment by lars-t-hansen** [comment]
After fixing #97, virtually all of the running time of sonar is spent in the ps pipeline.  It may be well worth our time to investigate the present issue further, so see if we can reduce the running time of sonar significantly.

**Comment by bast** [comment]
Good idea to read it directly instead of taking the detour via the shell.

**Comment by lars-t-hansen** [comment]
This is hard to benchmark precisely because there are all sorts of system effects, but it looks like a fairly naive implementation of this reduces the running time of sonar by about 50% (on my laptop).  I'll need to profile properly, and on a busier system, such as the login nodes of Fox.  But it's promising.  And also, there are untested optimization opportunities.  When sonar runs with --exclude-system-jobs, the system jobs can be excluded very early in the pipeline (the first stage enumerates pids and uids, and --exclude-system-jobs is a simple filter on uid).  Ditto for --exclude-users=root, this is also a uid filter.

The main source of uncertainty here is that my prototype does not map uid -> user name.  This strikes me as a potentially fairly expensive thing to do.  But unless there's an --exclude-users for unknown users in effect then user lookup can be deferred to the printing stage, where we'll do much less work than before (normally), and even if there is such an --exclude-users in effect then we can probably lookup just a few of those user names for their uids and filter by uids, and again defer user name generation until we print.

**Comment by bast** [comment]
Very good idea! Thanks!

**Comment by lars-t-hansen** [comment]
TODO list for my branch:

- [ ] Add filtering by UID
- [ ] Add late lookup of user names to map UID -> name (this is getpwuid_r (3))
- [ ] Add early lookup of UID to map name -> UID if required for filtering by name (this is getpwnam_r (3))
- [ ] The eprintln! in the code should probably be error returns and the caller should decide what to do about errors (probably: fallback to running ps, as now)
- [ ] Test cases
- [ ] Testing relative to the ps version, esp for some of the trickier data
- [ ] Test on various systems to iron out problems
